### ISSUE TITLE
Small tip

### ISSUE THREAD

**Issue by TheRedScreen64** [nosehad/My-Website#1]
Looks nice 👍
But why do you use complex js for the scrolling function and not just use  css and html?
It's a lot simpler

**Comment by nosehad** [comment]
> Looks nice 👍
> But why do you use complex js for the scrolling function and not just use  css and html?
> It's a lot simpler

I don't know l`ll probably start over again without using bootstrap and changing the layout, it's currently really messy. I guess I am also gonna switch to Tailwind CSS.

**Comment by TheRedScreen64** [comment]
Good idea
